"""empty message

Revision ID: b83e947d4b7d
Revises: b1f7d89dc503
Create Date: 2019-09-30 13:00:34.985891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83e947d4b7d'
down_revision = 'b1f7d89dc503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'rating')
    # ### end Alembic commands ###
